appId: ${APP_ID}
name: settings_live_activities_toggle_changes_and_persists
tags:
  - settings
---
- runFlow:
    file: ../common/launch_app_allow_notifications.yaml
- runFlow:
    file: ../common/open_settings.yaml
- scrollUntilVisible:
    element: "Enable Live Activities"
    direction: DOWN
- assertVisible:
    text: "Enable Live Activities"
    checked: true
- tapOn:
    id: "settings-live-activities-toggle"
    retryTapIfNoChange: true
- assertVisible:
    text: "Enable Live Activities"
    checked: false
- tapOn: "Save"
- runFlow:
    file: ../common/open_settings.yaml
- scrollUntilVisible:
    element: "Enable Live Activities"
    direction: DOWN
- assertVisible:
    text: "Enable Live Activities"
    checked: false
